### ISSUE TITLE
ASN1

### ISSUE THREAD

**Issue by yisRookie** [vitock/asn1#1]
兄弟 能指导下怎么用 oc 编码 ANS1

**Comment by Lorem3** [comment]
> 兄弟 能指导下怎么用 oc 编码 ANS1

如果只是paser 并读取对应字段 你可以 看看 
[test1 方法](https://github.com/vitock/asn1/blob/0adec8140a56bed26e12ed9a4f325e2d8baf680e/ASN1/ASN.m#L720)

编码的话,有些繁琐,建议你找找其他开源库.,应该有的

**Comment by yisRookie** [comment]
资料实在是少的可怜，目前用C++的方式弄的，不明所以，要是有OC的方式实现就好了
